<?php

namespace Zerp\Recruitment\Database\Seeders;

use Zerp\Recruitment\Models\JobPosting;
use Illuminate\Database\Seeder;
use Zerp\Hrm\Models\Branch;
use Zerp\Recruitment\Models\JobType;
use Zerp\Recruitment\Models\JobLocation;
use Zerp\Recruitment\Models\CustomQuestion;


class DemoJobPostingSeeder extends Seeder
{
    public function run($userId): void
    {
        if (JobPosting::where('created_by', $userId)->exists()) {
            return;
        }

        // Get required custom question IDs
        $requiredQuestionIds = CustomQuestion::where('created_by', $userId)
            ->where('is_active', 1)
            ->where('is_required', true)
            ->pluck('id')
            ->toArray();

        if (empty($requiredQuestionIds)) {
            return;
        }

        // Convert to JSON string for database storage
        $customQuestionsJson = json_encode($requiredQuestionIds);

        // Get available branches (some can be null)
        $branchIds = [];
        if (Module_is_active('Hrm', $userId)) {
            $branches = Branch::where('created_by', $userId)->get();
            $branchIds = $branches->pluck('id')->toArray();
        }

        $location = JobLocation::where('created_by', $userId)->where('status', 1)->pluck('id')->toArray();

        if (empty($location)) {
            return;
        }

        $jobPostings = [
            ['title' => 'Senior Full-Stack Developer', 'min_experience' => 5, 'max_experience' => 8, 'min_salary' => 85000.00, 'max_salary' => 125000.00, 'description' => '<p>Join our engineering team as a Senior Full-Stack Developer to architect and build next-generation web applications.</p>', 'requirements' => '<ul><li>5+ years full-stack development experience</li><li>Expertise in PHP, Laravel, Vue.js</li></ul>', 'benefits' => '<ul><li>Competitive salary with equity package</li><li>Health insurance</li></ul>', 'terms_condition' => '<p>Full-time position requiring occasional on-call duties.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(30)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'PHP,Laravel,Vue.js,TypeScript,MySQL'],
            ['title' => 'Digital Marketing Specialist', 'min_experience' => 3, 'max_experience' => 6, 'min_salary' => 65000.00, 'max_salary' => 90000.00, 'description' => '<p>Drive our digital presence as a Digital Marketing Specialist.</p>', 'requirements' => '<ul><li>3+ years digital marketing experience</li><li>Google Ads certification</li></ul>', 'benefits' => '<ul><li>Performance bonuses</li><li>Health insurance</li></ul>', 'terms_condition' => '<p>Full-time position with occasional travel.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->addDays(25)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(5)->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Google Ads,SEO,Analytics'],
            ['title' => 'Senior UX/UI Designer', 'min_experience' => 4, 'max_experience' => 7, 'min_salary' => 70000.00, 'max_salary' => 95000.00, 'description' => '<p>Lead user experience design for our core products.</p>', 'requirements' => '<ul><li>4+ years UX/UI design experience</li><li>Figma expertise</li></ul>', 'benefits' => '<ul><li>Creative freedom</li><li>Design conference budget</li></ul>', 'terms_condition' => '<p>Portfolio presentation required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(20)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(3)->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Figma,Adobe Creative Suite,User Research'],
            ['title' => 'Business Intelligence Analyst', 'min_experience' => 3, 'max_experience' => 6, 'min_salary' => 60000.00, 'max_salary' => 80000.00, 'description' => '<p>Transform raw data into strategic insights.</p>', 'requirements' => '<ul><li>SQL and Python proficiency</li><li>Tableau experience</li></ul>', 'benefits' => '<ul><li>Annual bonus potential</li><li>Learning budget</li></ul>', 'terms_condition' => '<p>Handle confidential data responsibly.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->addDays(35)->format('Y-m-d'), 'is_published' => false, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'SQL,Python,Tableau,Power BI'],
            ['title' => 'DevOps Engineer', 'min_experience' => 3, 'max_experience' => 6, 'min_salary' => 75000.00, 'max_salary' => 105000.00, 'description' => '<p>Build scalable, reliable systems.</p>', 'requirements' => '<ul><li>AWS/Azure expertise</li><li>Docker and Kubernetes</li></ul>', 'benefits' => '<ul><li>Certification reimbursement</li><li>On-call compensation</li></ul>', 'terms_condition' => '<p>On-call rotation responsibilities.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(40)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'AWS,Docker,Kubernetes,Terraform'],
            ['title' => 'HR Business Partner', 'min_experience' => 5, 'max_experience' => 8, 'min_salary' => 75000.00, 'max_salary' => 100000.00, 'description' => '<p>Support our growing organization with HR strategies.</p>', 'requirements' => '<ul><li>5+ years HR experience</li><li>SHRM certification preferred</li></ul>', 'benefits' => '<ul><li>Equity options</li><li>Flexible PTO</li></ul>', 'terms_condition' => '<p>Highest level of confidentiality required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(22)->format('Y-m-d'), 'is_published' => false, 'publish_date' => now()->subDays(4)->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'HRIS,Employment Law,Talent Management'],
            ['title' => 'Senior Sales Executive', 'min_experience' => 4, 'max_experience' => 8, 'min_salary' => 65000.00, 'max_salary' => 95000.00, 'description' => '<p>Drive revenue growth in our dynamic sales team.</p>', 'requirements' => '<ul><li>B2B sales experience</li><li>Salesforce proficiency</li></ul>', 'benefits' => '<ul><li>Uncapped commission</li><li>Sales incentive trips</li></ul>', 'terms_condition' => '<p>Travel requirements up to 50%.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->addDays(33)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(1)->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'B2B Sales,Salesforce,Negotiation'],
            ['title' => 'Software QA Engineer', 'min_experience' => 2, 'max_experience' => 5, 'min_salary' => 55000.00, 'max_salary' => 75000.00, 'description' => '<p>Ensure product quality through comprehensive testing.</p>', 'requirements' => '<ul><li>Automated testing tools</li><li>Agile methodologies</li></ul>', 'benefits' => '<ul><li>Performance bonuses</li><li>Modern testing tools</li></ul>', 'terms_condition' => '<p>Attention to detail required.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->addDays(45)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Selenium,Cypress,API Testing'],
            ['title' => 'Content Marketing Manager', 'min_experience' => 3, 'max_experience' => 6, 'min_salary' => 58000.00, 'max_salary' => 78000.00, 'description' => '<p>Lead our content marketing strategy.</p>', 'requirements' => '<ul><li>Content marketing experience</li><li>SEO knowledge</li></ul>', 'benefits' => '<ul><li>Creative freedom</li><li>Writing courses budget</li></ul>', 'terms_condition' => '<p>Portfolio review required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(30)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(2)->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Content Writing,SEO,Social Media'],
            ['title' => 'Data Scientist', 'min_experience' => 3, 'max_experience' => 6, 'min_salary' => 90000.00, 'max_salary' => 130000.00, 'description' => '<p>Extract insights from complex datasets.</p>', 'requirements' => '<ul><li>Python and R proficiency</li><li>Machine learning experience</li></ul>', 'benefits' => '<ul><li>Equity package</li><li>Conference attendance</li></ul>', 'terms_condition' => '<p>Advanced analytical skills required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(40)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Python,R,Machine Learning,Statistics'],
            ['title' => 'Project Manager', 'min_experience' => 4, 'max_experience' => 8, 'min_salary' => 70000.00, 'max_salary' => 95000.00, 'description' => '<p>Lead cross-functional projects.</p>', 'requirements' => '<ul><li>PMP certification preferred</li><li>JIRA experience</li></ul>', 'benefits' => '<ul><li>Performance bonuses</li><li>Leadership training</li></ul>', 'terms_condition' => '<p>Strong organizational skills required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(35)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(3)->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Project Management,PMP,Agile,JIRA'],
            ['title' => 'Cybersecurity Analyst', 'min_experience' => 2, 'max_experience' => 5, 'min_salary' => 65000.00, 'max_salary' => 90000.00, 'description' => '<p>Protect our organization from security threats.</p>', 'requirements' => '<ul><li>Security certifications</li><li>SIEM tools experience</li></ul>', 'benefits' => '<ul><li>Security clearance bonuses</li><li>Certification reimbursement</li></ul>', 'terms_condition' => '<p>Background check required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(50)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Cybersecurity,SIEM,Penetration Testing'],
            ['title' => 'Operations Manager', 'min_experience' => 5, 'max_experience' => 10, 'min_salary' => 75000.00, 'max_salary' => 105000.00, 'description' => '<p>Oversee daily operations and optimize processes.</p>', 'requirements' => '<ul><li>Operations management experience</li><li>ERP systems knowledge</li></ul>', 'benefits' => '<ul><li>Executive benefits</li><li>Stock options</li></ul>', 'terms_condition' => '<p>Leadership skills required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(25)->format('Y-m-d'), 'is_published' => false, 'publish_date' => now()->subDays(4)->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Operations Management,ERP,Leadership'],
            ['title' => 'Mobile App Developer', 'min_experience' => 3, 'max_experience' => 6, 'min_salary' => 70000.00, 'max_salary' => 100000.00, 'description' => '<p>Develop innovative mobile applications.</p>', 'requirements' => '<ul><li>iOS/Android development</li><li>React Native experience</li></ul>', 'benefits' => '<ul><li>Latest devices</li><li>Innovation time</li></ul>', 'terms_condition' => '<p>Stay current with mobile trends.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->addDays(30)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(1)->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'iOS,Android,React Native,Flutter'],
            ['title' => 'Legal Counsel', 'min_experience' => 5, 'max_experience' => 10, 'min_salary' => 120000.00, 'max_salary' => 180000.00, 'description' => '<p>Provide legal expertise for corporate matters.</p>', 'requirements' => '<ul><li>JD degree required</li><li>Corporate law experience</li></ul>', 'benefits' => '<ul><li>Executive benefits</li><li>Bar membership reimbursement</li></ul>', 'terms_condition' => '<p>Active bar membership required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(45)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Corporate Law,Contract Negotiation,Compliance'],
            ['title' => 'Cloud Solutions Architect', 'min_experience' => 6, 'max_experience' => 10, 'min_salary' => 110000.00, 'max_salary' => 150000.00, 'description' => '<p>Design and implement cloud solutions for large-scale systems.</p>', 'requirements' => '<ul><li>6+ years cloud architecture experience</li><li>AWS or Azure certification</li></ul>', 'benefits' => '<ul><li>Remote work options</li><li>Health insurance</li></ul>', 'terms_condition' => '<p>Travel required for client meetings.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(60)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'AWS,Azure,Cloud Architecture,DevOps'],
            ['title' => 'Data Engineer', 'min_experience' => 3, 'max_experience' => 6, 'min_salary' => 85000.00, 'max_salary' => 120000.00, 'description' => '<p>Design and implement data pipelines for scalable data systems.</p>', 'requirements' => '<ul><li>3+ years data engineering experience</li><li>Proficiency in Python, SQL</li></ul>', 'benefits' => '<ul><li>Flexible work hours</li><li>Conference attendance</li></ul>', 'terms_condition' => '<p>Collaborate with data science teams.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->addDays(50)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Python,SQL,Data Pipelines'],
            ['title' => 'Marketing Director', 'min_experience' => 8, 'max_experience' => 12, 'min_salary' => 130000.00, 'max_salary' => 180000.00, 'description' => '<p>Lead the marketing department and strategies.</p>', 'requirements' => '<ul><li>8+ years marketing leadership</li><li>Experience in digital marketing and analytics</li></ul>', 'benefits' => '<ul><li>Leadership bonuses</li><li>Health and wellness package</li></ul>', 'terms_condition' => '<p>Requires international travel.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(30)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Digital Marketing,Leadership,Analytics'],
            ['title' => 'Lead Backend Developer', 'min_experience' => 6, 'max_experience' => 10, 'min_salary' => 95000.00, 'max_salary' => 135000.00, 'description' => '<p>Lead the backend development team to build scalable systems.</p>', 'requirements' => '<ul><li>6+ years backend development experience</li><li>Expertise in Node.js, Python</li></ul>', 'benefits' => '<ul><li>Equity participation</li><li>Health benefits</li></ul>', 'terms_condition' => '<p>Must be comfortable with on-call rotations.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(45)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Node.js,Python,Microservices,API'],
            ['title' => 'Legal Operations Manager', 'min_experience' => 5, 'max_experience' => 8, 'min_salary' => 95000.00, 'max_salary' => 130000.00, 'description' => '<p>Oversee legal operations and compliance functions.</p>', 'requirements' => '<ul><li>5+ years legal operations experience</li><li>Strong organizational skills</li></ul>', 'benefits' => '<ul><li>Bonus opportunities</li><li>Paid time off</li></ul>', 'terms_condition' => '<p>High level of confidentiality required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(20)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Legal Operations,Compliance,Contract Management'],
            ['title' => 'Senior DevOps Engineer', 'min_experience' => 4, 'max_experience' => 7, 'min_salary' => 80000.00, 'max_salary' => 115000.00, 'description' => '<p>Automate deployment and infrastructure management.</p>', 'requirements' => '<ul><li>4+ years DevOps experience</li><li>Docker and Kubernetes expertise</li></ul>', 'benefits' => '<ul><li>Remote work flexibility</li><li>Tech allowance</li></ul>', 'terms_condition' => '<p>On-call support required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(35)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Docker,Kubernetes,CI/CD,AWS'],
            ['title' => 'Business Analyst', 'min_experience' => 3, 'max_experience' => 6, 'min_salary' => 60000.00, 'max_salary' => 85000.00, 'description' => '<p>Analyze business processes and requirements.</p>', 'requirements' => '<ul><li>3+ years business analysis experience</li><li>Strong analytical skills</li></ul>', 'benefits' => '<ul><li>Professional development</li><li>Health insurance</li></ul>', 'terms_condition' => '<p>Client interaction required.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->addDays(40)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(1)->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Business Analysis,Requirements Gathering,SQL'],
            ['title' => 'Quality Assurance Lead', 'min_experience' => 5, 'max_experience' => 8, 'min_salary' => 75000.00, 'max_salary' => 105000.00, 'description' => '<p>Lead QA team and ensure product quality.</p>', 'requirements' => '<ul><li>5+ years QA experience</li><li>Test automation expertise</li></ul>', 'benefits' => '<ul><li>Leadership training</li><li>Performance bonuses</li></ul>', 'terms_condition' => '<p>Team management experience required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(30)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Test Automation,Selenium,Leadership,JIRA'],
            ['title' => 'Financial Analyst', 'min_experience' => 2, 'max_experience' => 5, 'min_salary' => 55000.00, 'max_salary' => 80000.00, 'description' => '<p>Analyze financial data and create reports.</p>', 'requirements' => '<ul><li>2+ years finance experience</li><li>Excel and financial modeling skills</li></ul>', 'benefits' => '<ul><li>401k matching</li><li>Professional certifications</li></ul>', 'terms_condition' => '<p>CPA preferred but not required.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->addDays(25)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(2)->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Financial Analysis,Excel,Financial Modeling'],
            ['title' => 'Product Designer', 'min_experience' => 3, 'max_experience' => 6, 'min_salary' => 70000.00, 'max_salary' => 95000.00, 'description' => '<p>Design user-centered digital products.</p>', 'requirements' => '<ul><li>3+ years product design experience</li><li>Figma and prototyping skills</li></ul>', 'benefits' => '<ul><li>Design tools budget</li><li>Creative time</li></ul>', 'terms_condition' => '<p>Portfolio review required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(45)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Product Design,Figma,Prototyping,User Research'],
            ['title' => 'Sales Manager', 'min_experience' => 4, 'max_experience' => 8, 'min_salary' => 65000.00, 'max_salary' => 95000.00, 'description' => '<p>Lead sales team and drive revenue growth.</p>', 'requirements' => '<ul><li>4+ years sales management experience</li><li>CRM software proficiency</li></ul>', 'benefits' => '<ul><li>Commission structure</li><li>Sales incentives</li></ul>', 'terms_condition' => '<p>Travel required for client meetings.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(30)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(3)->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Sales Management,CRM,Lead Generation'],
            ['title' => 'Network Administrator', 'min_experience' => 3, 'max_experience' => 6, 'min_salary' => 60000.00, 'max_salary' => 85000.00, 'description' => '<p>Maintain and optimize network infrastructure.</p>', 'requirements' => '<ul><li>3+ years network administration</li><li>Cisco certification preferred</li></ul>', 'benefits' => '<ul><li>Certification reimbursement</li><li>Health benefits</li></ul>', 'terms_condition' => '<p>24/7 support rotation required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(35)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Network Administration,Cisco,TCP/IP,Firewall'],
            ['title' => 'Content Strategist', 'min_experience' => 3, 'max_experience' => 6, 'min_salary' => 55000.00, 'max_salary' => 75000.00, 'description' => '<p>Develop content strategies and editorial calendars.</p>', 'requirements' => '<ul><li>3+ years content strategy experience</li><li>SEO and analytics knowledge</li></ul>', 'benefits' => '<ul><li>Creative freedom</li><li>Professional development</li></ul>', 'terms_condition' => '<p>Writing samples required.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->addDays(40)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(1)->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Content Strategy,SEO,Analytics,Copywriting'],
            ['title' => 'Database Administrator', 'min_experience' => 4, 'max_experience' => 8, 'min_salary' => 75000.00, 'max_salary' => 105000.00, 'description' => '<p>Manage and optimize database systems.</p>', 'requirements' => '<ul><li>4+ years DBA experience</li><li>MySQL and PostgreSQL expertise</li></ul>', 'benefits' => '<ul><li>Database certification support</li><li>Flexible schedule</li></ul>', 'terms_condition' => '<p>Backup and recovery expertise required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(50)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'MySQL,PostgreSQL,Database Optimization,Backup Recovery'],
            ['title' => 'Technical Writer', 'min_experience' => 2, 'max_experience' => 5, 'min_salary' => 50000.00, 'max_salary' => 70000.00, 'description' => '<p>Create technical documentation and user guides.</p>', 'requirements' => '<ul><li>2+ years technical writing experience</li><li>API documentation experience</li></ul>', 'benefits' => '<ul><li>Remote work options</li><li>Writing tools budget</li></ul>', 'terms_condition' => '<p>Portfolio of technical writing required.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->addDays(30)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(2)->format('Y-m-d'), 'is_featured' => false, 'status' => 'active', 'skills' => 'Technical Writing,API Documentation,Markdown'],
            ['title' => 'Senior Data Analyst', 'min_experience' => 4, 'max_experience' => 7, 'min_salary' => 70000.00, 'max_salary' => 95000.00, 'description' => '<p>Lead data analysis initiatives and insights.</p>', 'requirements' => '<ul><li>4+ years data analysis experience</li><li>Advanced SQL skills</li></ul>', 'benefits' => '<ul><li>Data tools budget</li><li>Conference attendance</li></ul>', 'terms_condition' => '<p>Statistical knowledge required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(30)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(10)->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'SQL,Python,Statistics,Tableau'],
            ['title' => 'Product Manager', 'min_experience' => 5, 'max_experience' => 8, 'min_salary' => 90000.00, 'max_salary' => 120000.00, 'description' => '<p>Drive product strategy and roadmap.</p>', 'requirements' => '<ul><li>5+ years product management experience</li><li>Agile methodology knowledge</li></ul>', 'benefits' => '<ul><li>Equity package</li><li>Product conferences</li></ul>', 'terms_condition' => '<p>Strategic thinking required.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->addDays(25)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(15)->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Product Management,Agile,Strategy,Analytics'],
            ['title' => 'UX Researcher', 'min_experience' => 3, 'max_experience' => 6, 'min_salary' => 65000.00, 'max_salary' => 85000.00, 'description' => '<p>Conduct user research to inform design decisions.</p>', 'requirements' => '<ul><li>3+ years UX research experience</li><li>Research methodology expertise</li></ul>', 'benefits' => '<ul><li>Research tools budget</li><li>User conference attendance</li></ul>', 'terms_condition' => '<p>Research portfolio required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(35)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(12)->format('Y-m-d'), 'is_featured' => false, 'status' => 'active', 'skills' => 'User Research,Usability Testing,Analytics,Figma'],
            ['title' => 'Backend Engineer', 'min_experience' => 3, 'max_experience' => 6, 'min_salary' => 75000.00, 'max_salary' => 100000.00, 'description' => '<p>Build robust backend systems and APIs.</p>', 'requirements' => '<ul><li>3+ years backend development</li><li>Node.js or Python expertise</li></ul>', 'benefits' => '<ul><li>Tech stack freedom</li><li>Performance bonuses</li></ul>', 'terms_condition' => '<p>Code review participation required.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->addDays(20)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(8)->format('Y-m-d'), 'is_featured' => false, 'status' => 'active', 'skills' => 'Node.js,Python,API,Database'],
            ['title' => 'Operations Analyst', 'min_experience' => 2, 'max_experience' => 5, 'min_salary' => 55000.00, 'max_salary' => 75000.00, 'description' => '<p>Analyze and optimize operational processes.</p>', 'requirements' => '<ul><li>2+ years operations analysis</li><li>Process improvement experience</li></ul>', 'benefits' => '<ul><li>Process improvement bonuses</li><li>Training opportunities</li></ul>', 'terms_condition' => '<p>Analytical mindset required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(40)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(14)->format('Y-m-d'), 'is_featured' => false, 'status' => 'active', 'skills' => 'Process Improvement,Analytics,Excel,Operations'],
            ['title' => 'Software Engineer', 'min_experience' => 2, 'max_experience' => 5, 'min_salary' => 65000.00, 'max_salary' => 90000.00, 'description' => '<p>Develop and maintain software applications.</p>', 'requirements' => '<ul><li>2+ years software development</li><li>Full-stack capabilities</li></ul>', 'benefits' => '<ul><li>Stock options</li><li>Flexible work</li></ul>', 'terms_condition' => '<p>Team collaboration required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->subDays(10)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(30)->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'JavaScript,React,Node.js,SQL'],
            ['title' => 'Digital Marketing Manager', 'min_experience' => 4, 'max_experience' => 7, 'min_salary' => 70000.00, 'max_salary' => 95000.00, 'description' => '<p>Lead marketing campaigns and strategy.</p>', 'requirements' => '<ul><li>4+ years marketing management</li><li>Digital marketing expertise</li></ul>', 'benefits' => '<ul><li>Marketing budget</li><li>Team leadership</li></ul>', 'terms_condition' => '<p>Campaign management experience required.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->subDays(5)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(25)->format('Y-m-d'), 'is_featured' => false, 'status' => 'active', 'skills' => 'Digital Marketing,Campaign Management,Analytics,Leadership'],
            ['title' => 'System Administrator', 'min_experience' => 3, 'max_experience' => 6, 'min_salary' => 60000.00, 'max_salary' => 80000.00, 'description' => '<p>Maintain and manage IT infrastructure.</p>', 'requirements' => '<ul><li>3+ years system administration</li><li>Linux/Windows expertise</li></ul>', 'benefits' => '<ul><li>Certification support</li><li>On-call compensation</li></ul>', 'terms_condition' => '<p>24/7 availability required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->subDays(15)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(35)->format('Y-m-d'), 'is_featured' => false, 'status' => 'active', 'skills' => 'Linux,Windows,Networking,Security'],
            ['title' => 'Graphic Designer', 'min_experience' => 2, 'max_experience' => 5, 'min_salary' => 45000.00, 'max_salary' => 65000.00, 'description' => '<p>Create visual designs for marketing materials.</p>', 'requirements' => '<ul><li>2+ years graphic design experience</li><li>Adobe Creative Suite proficiency</li></ul>', 'benefits' => '<ul><li>Creative freedom</li><li>Design software budget</li></ul>', 'terms_condition' => '<p>Portfolio review required.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->subDays(20)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(40)->format('Y-m-d'), 'is_featured' => true, 'status' => 'active', 'skills' => 'Adobe Creative Suite,Graphic Design,Branding,Print Design'],
            ['title' => 'Business Development Manager', 'min_experience' => 4, 'max_experience' => 8, 'min_salary' => 75000.00, 'max_salary' => 105000.00, 'description' => '<p>Drive business growth and partnerships.</p>', 'requirements' => '<ul><li>4+ years business development</li><li>Partnership management experience</li></ul>', 'benefits' => '<ul><li>Commission structure</li><li>Travel allowance</li></ul>', 'terms_condition' => '<p>Networking skills required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->subDays(8)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(28)->format('Y-m-d'), 'is_featured' => false, 'status' => 'active', 'skills' => 'Business Development,Partnership Management,Sales,Negotiation'],
            ['title' => 'Junior Data Scientist', 'min_experience' => 1, 'max_experience' => 3, 'min_salary' => 60000.00, 'max_salary' => 80000.00, 'description' => '<p>Support data science initiatives and analysis.</p>', 'requirements' => '<ul><li>1+ years data science experience</li><li>Python and statistics knowledge</li></ul>', 'benefits' => '<ul><li>Learning opportunities</li><li>Mentorship program</li></ul>', 'terms_condition' => '<p>Continuous learning required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->subDays(30)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(50)->format('Y-m-d'), 'is_featured' => false, 'status' => 'active', 'skills' => 'Python,Statistics,Machine Learning,SQL'],
            ['title' => 'Social Media Manager', 'min_experience' => 2, 'max_experience' => 5, 'min_salary' => 45000.00, 'max_salary' => 65000.00, 'description' => '<p>Manage social media presence and campaigns.</p>', 'requirements' => '<ul><li>2+ years social media management</li><li>Content creation skills</li></ul>', 'benefits' => '<ul><li>Creative freedom</li><li>Social media tools</li></ul>', 'terms_condition' => '<p>Social media expertise required.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->subDays(25)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(45)->format('Y-m-d'), 'is_featured' => false, 'status' => 'active', 'skills' => 'Social Media,Content Creation,Analytics,Community Management'],
            ['title' => 'Web Developer', 'min_experience' => 2, 'max_experience' => 4, 'min_salary' => 50000.00, 'max_salary' => 70000.00, 'description' => '<p>Develop and maintain web applications.</p>', 'requirements' => '<ul><li>2+ years web development</li><li>HTML, CSS, JavaScript proficiency</li></ul>', 'benefits' => '<ul><li>Remote work options</li><li>Tech allowance</li></ul>', 'terms_condition' => '<p>Portfolio review required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->subDays(35)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(55)->format('Y-m-d'), 'is_featured' => false, 'status' => 'active', 'skills' => 'HTML,CSS,JavaScript,PHP'],
            ['title' => 'HR Coordinator', 'min_experience' => 1, 'max_experience' => 3, 'min_salary' => 40000.00, 'max_salary' => 55000.00, 'description' => '<p>Support HR operations and employee relations.</p>', 'requirements' => '<ul><li>1+ years HR experience</li><li>HRIS knowledge preferred</li></ul>', 'benefits' => '<ul><li>HR certification support</li><li>Professional development</li></ul>', 'terms_condition' => '<p>Confidentiality required.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->subDays(20)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(40)->format('Y-m-d'), 'is_featured' => false, 'status' => 'active', 'skills' => 'HR Operations,HRIS,Employee Relations,Recruitment'],
            ['title' => 'Sales Representative', 'min_experience' => 1, 'max_experience' => 4, 'min_salary' => 40000.00, 'max_salary' => 60000.00, 'description' => '<p>Generate leads and close sales deals.</p>', 'requirements' => '<ul><li>1+ years sales experience</li><li>CRM software knowledge</li></ul>', 'benefits' => '<ul><li>Commission structure</li><li>Sales training</li></ul>', 'terms_condition' => '<p>Sales targets required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->subDays(40)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(60)->format('Y-m-d'), 'is_featured' => false, 'status' => 'active', 'skills' => 'Sales,CRM,Lead Generation,Communication'],

            // Status 0 - Draft
            ['title' => 'Junior Frontend Developer', 'min_experience' => 1, 'max_experience' => 3, 'min_salary' => 45000.00, 'max_salary' => 65000.00, 'description' => '<p>Join our frontend team as a junior developer.</p>', 'requirements' => '<ul><li>1+ years frontend experience</li><li>React knowledge</li></ul>', 'benefits' => '<ul><li>Mentorship program</li><li>Learning budget</li></ul>', 'terms_condition' => '<p>Willingness to learn required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(30)->format('Y-m-d'), 'is_published' => false, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => false, 'status' => 'draft', 'skills' => 'React,JavaScript,HTML,CSS'],
            ['title' => 'Marketing Coordinator', 'min_experience' => 1, 'max_experience' => 3, 'min_salary' => 40000.00, 'max_salary' => 55000.00, 'description' => '<p>Support marketing campaigns and initiatives.</p>', 'requirements' => '<ul><li>1+ years marketing experience</li><li>Social media knowledge</li></ul>', 'benefits' => '<ul><li>Creative environment</li><li>Growth opportunities</li></ul>', 'terms_condition' => '<p>Creative mindset required.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->addDays(25)->format('Y-m-d'), 'is_published' => false, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => false, 'status' => 'draft', 'skills' => 'Social Media,Content Creation,Analytics'],
            ['title' => 'IT Support Specialist', 'min_experience' => 2, 'max_experience' => 4, 'min_salary' => 45000.00, 'max_salary' => 60000.00, 'description' => '<p>Provide technical support to internal teams.</p>', 'requirements' => '<ul><li>2+ years IT support experience</li><li>Windows/Mac proficiency</li></ul>', 'benefits' => '<ul><li>Certification support</li><li>Flexible hours</li></ul>', 'terms_condition' => '<p>Problem-solving skills required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(35)->format('Y-m-d'), 'is_published' => false, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => false, 'status' => 'draft', 'skills' => 'Windows,Mac,Troubleshooting,Help Desk'],
            ['title' => 'Accounting Assistant', 'min_experience' => 1, 'max_experience' => 3, 'min_salary' => 38000.00, 'max_salary' => 50000.00, 'description' => '<p>Assist with daily accounting operations.</p>', 'requirements' => '<ul><li>1+ years accounting experience</li><li>QuickBooks knowledge</li></ul>', 'benefits' => '<ul><li>Professional development</li><li>Health benefits</li></ul>', 'terms_condition' => '<p>Attention to detail required.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->addDays(20)->format('Y-m-d'), 'is_published' => false, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => false, 'status' => 'draft', 'skills' => 'QuickBooks,Excel,Accounting,Data Entry'],
            ['title' => 'Customer Success Manager', 'min_experience' => 3, 'max_experience' => 5, 'min_salary' => 55000.00, 'max_salary' => 75000.00, 'description' => '<p>Ensure customer satisfaction and retention.</p>', 'requirements' => '<ul><li>3+ years customer success experience</li><li>CRM proficiency</li></ul>', 'benefits' => '<ul><li>Customer bonuses</li><li>Travel opportunities</li></ul>', 'terms_condition' => '<p>Strong communication skills required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->addDays(40)->format('Y-m-d'), 'is_published' => false, 'publish_date' => now()->format('Y-m-d'), 'is_featured' => false, 'status' => 'draft', 'skills' => 'Customer Success,CRM,Communication,Retention'],

            // Status 5 - Closed
            ['title' => 'Senior Software Architect', 'min_experience' => 8, 'max_experience' => 12, 'min_salary' => 120000.00, 'max_salary' => 160000.00, 'description' => '<p>Design and oversee software architecture.</p>', 'requirements' => '<ul><li>8+ years software architecture</li><li>Enterprise system design</li></ul>', 'benefits' => '<ul><li>Executive benefits</li><li>Architecture conferences</li></ul>', 'terms_condition' => '<p>Leadership experience required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->subDays(60)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(80)->format('Y-m-d'), 'is_featured' => true, 'status' => 'draft', 'skills' => 'Software Architecture,Enterprise Design,Leadership,Microservices'],
            ['title' => 'VP of Marketing', 'min_experience' => 10, 'max_experience' => 15, 'min_salary' => 150000.00, 'max_salary' => 200000.00, 'description' => '<p>Lead marketing strategy and team.</p>', 'requirements' => '<ul><li>10+ years marketing leadership</li><li>Strategic planning experience</li></ul>', 'benefits' => '<ul><li>Executive package</li><li>Equity participation</li></ul>', 'terms_condition' => '<p>Executive leadership required.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->subDays(45)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(65)->format('Y-m-d'), 'is_featured' => true, 'status' => 'draft', 'skills' => 'Marketing Leadership,Strategic Planning,Team Management,Brand Strategy'],
            ['title' => 'Chief Technology Officer', 'min_experience' => 12, 'max_experience' => 20, 'min_salary' => 180000.00, 'max_salary' => 250000.00, 'description' => '<p>Lead technology strategy and innovation.</p>', 'requirements' => '<ul><li>12+ years technology leadership</li><li>Strategic technology planning</li></ul>', 'benefits' => '<ul><li>Executive compensation</li><li>Equity package</li></ul>', 'terms_condition' => '<p>C-level experience required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->subDays(90)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(110)->format('Y-m-d'), 'is_featured' => true, 'status' => 'draft', 'skills' => 'Technology Leadership,Strategic Planning,Innovation,Team Building'],
            ['title' => 'Senior Financial Controller', 'min_experience' => 7, 'max_experience' => 10, 'min_salary' => 95000.00, 'max_salary' => 130000.00, 'description' => '<p>Oversee financial operations and reporting.</p>', 'requirements' => '<ul><li>7+ years financial management</li><li>CPA certification required</li></ul>', 'benefits' => '<ul><li>Executive benefits</li><li>Professional development</li></ul>', 'terms_condition' => '<p>CPA license required.</p>', 'show_terms_condition' => false, 'application_deadline' => now()->subDays(70)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(90)->format('Y-m-d'), 'is_featured' => false, 'status' => 'draft', 'skills' => 'Financial Management,CPA,Financial Reporting,Budgeting'],
            ['title' => 'Director of Operations', 'min_experience' => 8, 'max_experience' => 12, 'min_salary' => 110000.00, 'max_salary' => 145000.00, 'description' => '<p>Direct operational strategy and execution.</p>', 'requirements' => '<ul><li>8+ years operations leadership</li><li>Process optimization experience</li></ul>', 'benefits' => '<ul><li>Leadership bonuses</li><li>Executive training</li></ul>', 'terms_condition' => '<p>Operations leadership required.</p>', 'show_terms_condition' => true, 'application_deadline' => now()->subDays(55)->format('Y-m-d'), 'is_published' => true, 'publish_date' => now()->subDays(75)->format('Y-m-d'), 'is_featured' => true, 'status' => 'draft', 'skills' => 'Operations Leadership,Process Optimization,Strategic Planning,Team Management'],
        ];

        // Ensure at least one job type exists
        $jobType = JobType::where('created_by', $userId)->where('is_active', 1)->first();
        if (!$jobType) {
            $jobType = JobType::create([
                'name' => 'Full Time',
                'description' => 'Full-time employment',
                'is_active' => true,
                'creator_id' => $userId,
                'created_by' => $userId,
            ]);
        }

        foreach ($jobPostings as $index => $posting) {
            // Assign specific branch based on role
            $branchName = match ($posting['title']) {
                'Senior Full-Stack Developer', 'Senior UX/UI Designer', 'Business Intelligence Analyst', 'DevOps Engineer', 'Data Scientist', 'Mobile App Developer' => 'Technology Branch',
                'Digital Marketing Specialist', 'Content Marketing Manager', 'Senior Sales Executive' => 'Marketing Branch',
                'HR Business Partner' => 'HR Branch',
                'Software QA Engineer', 'Cybersecurity Analyst' => 'Quality Branch',
                'Project Manager', 'Operations Manager' => 'Operations Branch',
                'Legal Counsel' => 'Legal Branch',
                default => null
            };

            // Get specific branch ID if exists
            $specificBranchId = null;
            if ($branchName && Module_is_active('Hrm', $userId)) {
                $branch = Branch::where('created_by', $userId)
                    ->where('branch_name', $branchName)
                    ->first();
                $specificBranchId = $branch?->id;
            }

            // Generate realistic data for specific fields
            $code = 'JOB' . str_pad($index + 1, 4, '0', STR_PAD_LEFT);
            $position = fake()->numberBetween(1, 5);
            $priority = fake()->randomElement(['0', '1', '2']); // 0=Low, 1=Medium, 2=High
            $jobApplication = fake()->randomElement(['existing', 'custom']);
            $applicationUrl = $jobApplication === 'custom' ? fake()->url() : null;

            // Realistic applicant fields based on job type
            $applicant = json_encode(fake()->randomElements(['gender', 'date_of_birth', 'country'], fake()->numberBetween(0, 3)));

            // Realistic visibility fields
            $visibility = json_encode(fake()->randomElements(['profile_image', 'resume', 'cover_letter'], fake()->numberBetween(1, 3)));

            // Get branch ID - use specific branch if found, otherwise random from available branches, or null
            $branchId = $specificBranchId ?? (!empty($branchIds) ? fake()->randomElement($branchIds) : null);

            JobPosting::create(array_merge($posting, [
                'code' => $code,
                'posting_code' => JobPosting::generatePostingCode($userId),
                'position' => $position,
                'priority' => $priority,
                'job_application' => $jobApplication,
                'application_url' => $applicationUrl,
                'applicant' => $applicant,
                'visibility' => $visibility,
                'branch_id' => $branchId,
                'job_type_id' => $jobType->id,
                'location_id' => fake()->randomElement($location),
                'custom_questions' => $customQuestionsJson,
                'creator_id' => $userId,
                'created_by' => $userId,
            ]));
        }
    }
}
